### ISSUE TITLE
Rewrite GameplaySetupMenu

### ISSUE THREAD

**Issue by CGray1234** [CGray1234/InGameText#7]
I will be rewriting the GameplaySetupMenu to be similar to Qosmetic's UI (clicking a button that takes you to the settings)

### TODO:

- [x] Remove images in the settings UI and use them as buttons in the GameplaySetupMenu
- [x] Add position button
- [x] Add rotation button
- [x] Add miscellaneous button
- [x] Fix game crashing when a button is pressed (see comment)
- [x] Make screens
- [x] Make buttons make different screens appear, also add a back button.
- [x] Move buttons so they aren't overlapping
- [x] Replace buttons with new images
- [x] GitHub repo link (not adding)

**Comment by CGray1234** [comment]
### UPDATE:

As of 12/8/2022, the menu will not take you to the InGameText settings. There will be different setting screens built into the GameplaySetupMenu. This will make the update easier to accomplish, will fix the crash, and in my opinion be less annoying to be taken to the settings and then have to find the song you want.

**Comment by CGray1234** [comment]
Closing when new build is released

**Comment by CGray1234** [comment]
Forgot to close
